### ISSUE TITLE
How to start to use PyNAFF?

### ISSUE THREAD

**Issue by Landau1908** [nkarast/PyNAFF#1]
Hi, Nikos!

This is the my first time to use NAFF as a tool to analyze TBT data, and at this moment I can't run the code with a small sample routine anywhere.

I simulate the TBT data using a decayed sinusoidal, which records one data each turn, so the obtained data is one-dimensional. 

Below is the sample code. B.T.W., I copy the PyNAFF.py to my current directory and imported it as a module.

```python
import numpy as np
import scipy as sp
import matplotlib.pylab as plt
import PyNAFF as pnf
#import PyNAFF.Cython.PyNAFF as cpnf

q = 2.1#tune
f0 = 1e6#revolution frequency
N = 2**11#total sample number

sample_rate=10e6
sample_time = N/sample_rate

tau = sample_time/5#decay const.

t = np.linspace(0, sample_time, N)
y = np.sin(2*np.pi*q*f0*t)*(np.exp(-t/tau))
#plt.plot(y,"b.")

turns=len(y)
result = pnf.naff(data=y, turns=turns, nterm=1, icol=1, icx=1, icy=0, saveFiles=False, doAll=False, neps=100000000., loglevel=20, logfile=None, debug=False, batch=True,
         icplx=1, iw=+1, nulin=0,  iprnaf=0, iftes=0, ifsav=0, ifcomp=0, ifres=0, ifstab=1,imodt=0, inputParamFile=None, solutionFile='track.sol',
         parametersOutLog='nafpar.par', outBuffFile='naf.out', tabFile='naf.tab')
```
The Exception says 
```python
Traceback (most recent call last):

  File "<ipython-input-3-47671462eba5>", line 4, in <module>
    parametersOutLog='nafpar.par', outBuffFile='naf.out', tabFile='naf.tab')

  File "E:\CSRm_BPM_data\BPM_signal_2011\naff_test\PyNAFF.py", line 1540, in naff
    raise ValueError("# PyNAFF.naff() : Number of turns [{}] exceeds the minimum required data length [{}]".format(turns, len(data+1)))

ValueError: # PyNAFF.naff() : Number of turns [2048] exceeds the minimum required data length [2048]
```
Regards!
Yongchun

**Comment by nkarast** [comment]
Hi Yongcung,

I pushed the latest version of PyNAFF (complete restructure).
Please have a look at the README and the linked example, and let me know if your problem insists.

cheers
NK
